naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: xIIUtiIxl8QCwV_I7xMz
    secret: X8mLnvTeUO